"""add cover_image to posts

Revision ID: 5102b4a37c63
Revises: 886bec1f9d63
Create Date: 2026-09-29 16:03:59.338531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5102b4a37c63'
down_revision: Union[str, Sequence[str], None] = '886bec1f9d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('cover_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'cover_image')
    # ### end Alembic commands ###
